# Generated by Django 4.2.7 on 2023-12-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1200)),
                ('contents', models.TextField(default='값을 넣어주세요', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_upload', models.FileField(blank=True, upload_to='board/images/%Y/%m/%d')),
                ('Board_Status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='값을 넣어주세요', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_predict_future_Data_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_predictData_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_rawdata_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('avg_temp', models.FloatField()),
                ('avg_max_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.temp_rawdata_storage')),
            ],
        ),
        migrations.CreateModel(
            name='temp_predictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('avg_temp', models.FloatField()),
                ('avg_max_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('pre_avg_temp', models.FloatField()),
                ('pre_avg_max_temp', models.FloatField()),
                ('pre_avg_min_temp', models.FloatField()),
                ('rawdata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.temp_rawdata')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.temp_predictdata_storage')),
            ],
        ),
        migrations.CreateModel(
            name='temp_predict_future_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('pre_avg_temp', models.FloatField()),
                ('pre_avg_max_temp', models.FloatField()),
                ('pre_avg_min_temp', models.FloatField()),
                ('rawdata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.temp_rawdata')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.temp_predict_future_data_storage')),
            ],
        ),
    ]
