# Generated by Django 4.2.7 on 2023-12-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ele_rawdata_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ele_rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trial', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('total_use', models.FloatField()),
                ('total_price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.ele_rawdata_storage')),
            ],
        ),
    ]
