# Generated by Django 4.2.7 on 2023-12-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict_future_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('pre_avg_temp', models.FloatField()),
                ('pre_avg_max_temp', models.FloatField()),
                ('pre_avg_min_temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='predictData_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='predictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('avg_temp', models.FloatField()),
                ('avg_max_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('pre_avg_temp', models.FloatField()),
                ('pre_avg_max_temp', models.FloatField()),
                ('pre_avg_min_temp', models.FloatField()),
                ('storage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.predictdata_storage')),
            ],
        ),
    ]
