# Generated by Django 4.2.7 on 2023-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_ele_rawdata_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ele_rawdata',
            name='avg_price',
            field=models.CharField(max_length=255),
        ),
    ]
