# Generated by Django 4.2.7 on 2023-11-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_email_member_tell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
