# Generated by Django 4.2.7 on 2023-11-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_category_board_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Address',
        ),
    ]
