# Generated by Django 4.2.7 on 2023-11-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_board_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(default='값을 넣어주세요', max_length=2000),
        ),
    ]
