# Generated by Django 4.2.7 on 2023-11-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_board_contents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
