# Generated by Django 4.2.7 on 2023-11-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_delete_board_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Tell',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
