# Generated by Django 4.2.7 on 2023-12-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_tell_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
    ]
