# Generated by Django 4.2.7 on 2023-12-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_member_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
